---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  interval: 10m
  chart:
    spec:
      chart: apache
      version: 8.12.1
      sourceRef:
        kind: HelmRepository
        name: apache
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
    service:
      type: NodePort
