---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
spec:
  releaseName: apache-apache
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: apache
    version: 8.12.1
  values:
    replicaCount: 3
    service:
      type: NodePort
